In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

ONE HOT REPRESENTATION

In [6]:
# now i have to convert into one hot representation
voc_size=10000;
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[2892, 3118, 6419, 4748], [2892, 3118, 6419, 7815], [2892, 888, 6419, 1392], [8652, 2555, 8321, 4602, 6614], [8652, 2555, 8321, 4602, 5308], [9365, 2892, 4042, 6419, 4649], [5542, 3063, 9615, 4602]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2892 3118 6419 4748]
 [   0    0    0    0 2892 3118 6419 7815]
 [   0    0    0    0 2892  888 6419 1392]
 [   0    0    0 8652 2555 8321 4602 6614]
 [   0    0    0 8652 2555 8321 4602 5308]
 [   0    0    0 9365 2892 4042 6419 4649]
 [   0    0    0    0 5542 3063 9615 4602]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:

print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step
[[[-0.00911403  0.03133908  0.04938444  0.03255007 -0.02914853
   -0.03440536 -0.01043584  0.03065399  0.01638502  0.02648645]
  [-0.00911403  0.03133908  0.04938444  0.03255007 -0.02914853
   -0.03440536 -0.01043584  0.03065399  0.01638502  0.02648645]
  [-0.00911403  0.03133908  0.04938444  0.03255007 -0.02914853
   -0.03440536 -0.01043584  0.03065399  0.01638502  0.02648645]
  [-0.00911403  0.03133908  0.04938444  0.03255007 -0.02914853
   -0.03440536 -0.01043584  0.03065399  0.01638502  0.02648645]
  [-0.04915714 -0.04860485 -0.03305304  0.03000374  0.02939211
    0.04359703 -0.02230208  0.00247208 -0.00377206 -0.03705312]
  [-0.02261295  0.04353899 -0.01383086 -0.04810054  0.03712637
    0.01187718  0.02362305 -0.0400404  -0.01296387  0.02773222]
  [ 0.04331905  0.02157617 -0.02249445  0.00150837  0.02472328
   -0.02578157  0.0402427  -0.02582777  0.0060739  -0.0063184 ]
  [ 0.01766438 -0.0073904   0.00527902 -0.03036783  0.00732861
   -0.025

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2892, 3118, 6419, 4748], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
[[-0.00911403  0.03133908  0.04938444  0.03255007 -0.02914853 -0.03440536
  -0.01043584  0.03065399  0.01638502  0.02648645]
 [-0.00911403  0.03133908  0.04938444  0.03255007 -0.02914853 -0.03440536
  -0.01043584  0.03065399  0.01638502  0.02648645]
 [-0.00911403  0.03133908  0.04938444  0.03255007 -0.02914853 -0.03440536
  -0.01043584  0.03065399  0.01638502  0.02648645]
 [-0.00911403  0.03133908  0.04938444  0.03255007 -0.02914853 -0.03440536
  -0.01043584  0.03065399  0.01638502  0.02648645]
 [-0.04915714 -0.04860485 -0.03305304  0.03000374  0.02939211  0.04359703
  -0.02230208  0.00247208 -0.00377206 -0.03705312]
 [-0.02261295  0.04353899 -0.01383086 -0.04810054  0.03712637  0.01187718
   0.02362305 -0.0400404  -0.01296387  0.02773222]
 [ 0.04331905  0.02157617 -0.02249445  0.00150837  0.02472328 -0.02578157
   0.0402427  -0.02582777  0.0060739  -0.0063184 ]
 [ 0.01766438 -0.0073904   0.00527902 -0.03036783  0.00732861 -0.02507541
   0.0430952 